### ISSUE TITLE
Missing total population size considered

### ISSUE THREAD

**Issue by Maxwell-ihiaso** [Ernest-30/COVID19-Report-Analysis#1]
@Ernest-30 thanks for taking time to prepare this analysis.

I noticed a 71% Infection. I have checked the data visualization to try to get the total population sized that this was based on, and was unable to find one.

Could you include this information to the report?

**Comment by Ernest-30** [comment]
@Maxwell-ihiaso the total population considered has been included in the report and the infection rate has also been updated. Thanks for pointing this out.
